---
- name: Odinstaluj NGINX
  apt:
    name: "{{ nginx_package_name }}"
    state: absent

- name: Usuń plik konfiguracyjny NGINX
  file:
    path: "{{ nginx_config_dest }}"
    state: absent

- name: Usuń plik HTML
  file:
    path: "{{ nginx_html_dest }}"
    state: absent
